name: test

on:
  push:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Error Check
      - name: make deploy
        run: sudo make deploy

      - name: source ~/.zshrc
        run: sudo source ~/.zshrc
